# SwiftLint configuration for enforcing design tokens usage
# - Tokens live in Design/DesignSystem.swift (Spacing, AppColors, Typography)
# - These rules are initially warnings to avoid breaking builds prior to codemod migration
# - After migration, consider elevating select rules to `error`

# Limit linting to app source (exclude generated, external, and scripts)
included:
  - I Do Blueprint
excluded:
  - Packages
  - Scripts
  - supabase
  - .build
  - DerivedData

reporter: "xcode"

# Adopt recommended opt-in rules (kept lean and pragmatic for this app)
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - discouraged_optional_boolean
  - empty_count
  - explicit_enum_raw_value
  - explicit_init
  - file_types_order
  - implicit_return
  - redundant_nil_coalescing
  - redundant_type_annotation
  - yoda_condition
  - prefer_self_type_over_type_of_self

# Rule configurations
line_length:
  warning: 120
  error: 160
  ignores_comments: true
  ignores_urls: true
  ignores_interpolated_strings: true

identifier_name:
  min_length:
    warning: 2
    error: 1
  excluded: [id, x, y, to, vc]
  allowed_symbols: ["_"]

type_name:
  min_length: 3
  max_length:
    warning: 50
    error: 60
  excluded: [id, URL, JSON]

file_length:
  warning: 400
  error: 800

type_body_length:
  warning: 300
  error: 600

function_body_length:
  warning: 80
  error: 120

function_parameter_count:
  warning: 8
  error: 10

cyclomatic_complexity:
  warning: 12
  error: 20

nesting:
  type_level:
    warning: 2
    error: 3

file_types_order:
  excluded:
    - "I Do Blueprint/Design/**"
    - "I Do Blueprint/App/RootFlowView.swift"

# Custom rules focused on design system enforcement
custom_rules:
  no_literal_rgb_colors:
    name: "No literal RGB/white Color initializer"
    regex: "\\bColor\\s*\\(\\s*(red|green|blue|white)\\s*:"
    message: "Use AppColors tokens (semantic colors) instead of literal RGB/white initializers."
    included:
      - I Do Blueprint/Views
      - I Do Blueprint/I Do Blueprint/Views
      - I Do Blueprint/App
      - I Do Blueprint/Services
    excluded:
      - I Do Blueprint/Design/ColorPalette.swift
      - I Do Blueprint/Domain
    severity: error

  no_basic_foreground_colors:
    name: "No basic foregroundColor(.gray/.black/.white)"
    regex: "\\.foregroundColor\\s*\\(\\s*\\.(black|white|gray)\\s*\\)"
    message: "Use semantic colors from AppColors (e.g., textPrimary/textSecondary/primary)."
    included:
      - I Do Blueprint/Views
      - I Do Blueprint/I Do Blueprint/Views
      - I Do Blueprint/App
      - I Do Blueprint/Services
    severity: error

  no_numeric_padding:
    name: "No numeric padding"
    regex: "\\.padding\\s*\\(\\s*(?:\\.[A-Za-z]+\\s*,\\s*)?\\d+(?:\\.\\d+)?\\s*\\)"
    message: "Use Spacing.* tokens instead of numeric literals in padding."
    included:
      - I Do Blueprint/Views
      - I Do Blueprint/I Do Blueprint/Views
      - I Do Blueprint/App
      - I Do Blueprint/Services
    severity: error

  no_custom_font:
    name: "No .font(.custom)"
    regex: "\\.font\\s*\\(\\s*\\.custom\\s*\\("
    message: "Use Typography tokens instead of .font(.custom)."
    included:
      - I Do Blueprint/Views
      - I Do Blueprint/I Do Blueprint/Views
      - I Do Blueprint/App
      - I Do Blueprint/Services
    severity: error
