# SwiftLint configuration for enforcing design tokens usage
# - Tokens live in Design/DesignSystem.swift (Spacing, AppColors, Typography)
# - These rules are initially warnings to avoid breaking builds prior to codemod migration
# - After migration, consider elevating select rules to `error`

# Limit linting to app source (exclude generated, external, and scripts)
included:
  - I Do Blueprint
excluded:
  - Packages
  - Scripts
  - supabase
  - .build
  - DerivedData

reporter: "xcode"

# Disabled rules (conflicts or not applicable)
disabled_rules:
  - redundant_string_enum_value  # Conflicts with explicit_enum_raw_value
  - multiple_closures_with_trailing_closure  # SwiftUI idiom, improves readability
  - discouraged_optional_boolean  # Necessary for database models and API responses
  - attributes  # Formatting preference, minimal value
  - trailing_whitespace  # Formatting only, no functional impact
  - colon  # Formatting only, no functional impact
  - trailing_newline  # Formatting only, no functional impact
  - trailing_comma  # Style preference, no functional impact
  - vertical_whitespace  # Formatting only, no functional impact
  - implicit_optional_initialization  # var x: Int? = nil is clear
  - for_where  # Sometimes if inside for is clearer
  - unused_closure_parameter  # Sometimes parameter name adds clarity
  - implicit_return  # Explicit returns can be clearer
  - array_init  # .map { $0 } is idiomatic
  - large_tuple  # Sometimes tuples are appropriate
  - file_length  # Some files are legitimately large
  - type_body_length  # Some types are legitimately large
  - function_body_length  # Some functions are legitimately long
  - cyclomatic_complexity  # Some functions are legitimately complex
  - closure_end_indentation  # Formatting preference
  - unused_optional_binding  # let _ = is sometimes clearer
  - redundant_type_annotation  # Sometimes explicit types add clarity
  - todo  # TODOs are tracked separately
  - orphaned_doc_comment  # Sometimes intentional
  - unused_enumerated  # Sometimes enumerated adds clarity
  - blanket_disable_command  # Intentional disables are documented
  - nesting  # Sometimes nesting is appropriate
  - unneeded_synthesized_initializer  # Sometimes explicit is clearer
  - explicit_init  # Sometimes .init() is clearer
  - switch_case_alignment  # Formatting preference

# Adopt recommended opt-in rules (kept lean and pragmatic for this app)
opt_in_rules:
  # - array_init  # Disabled: .map { $0 } is idiomatic
  # - attributes  # Disabled: formatting preference, minimal value
  # - closure_end_indentation  # Disabled: formatting preference
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  # - discouraged_optional_boolean  # Disabled: necessary for database models
  - empty_count
  - explicit_enum_raw_value
  # - explicit_init  # Disabled: sometimes .init() is clearer
  # - file_types_order  # Disabled: 233 violations, semantic organization preferred
  # - implicit_return  # Disabled: explicit returns can be clearer
  - redundant_nil_coalescing
  # - redundant_type_annotation  # Disabled: sometimes explicit types add clarity
  - yoda_condition
  - prefer_self_type_over_type_of_self

# Rule configurations
line_length:
  warning: 160  # Increased to match error threshold
  error: 200
  ignores_comments: true
  ignores_urls: true
  ignores_interpolated_strings: true

identifier_name:
  min_length:
    warning: 2
    error: 1
  excluded: [id, x, y, to, vc, r, g, b, a, i, j, k, w, h, s, e, p, c]  # Common: RGB, indices, dimensions
  allowed_symbols: ["_"]

type_name:
  min_length: 3
  max_length:
    warning: 50
    error: 60
  excluded: [id, URL, JSON]

file_length:
  warning: 400
  error: 800

type_body_length:
  warning: 300
  error: 600

function_body_length:
  warning: 80
  error: 120

function_parameter_count:
  warning: 8
  error: 10

cyclomatic_complexity:
  warning: 12
  error: 20

nesting:
  type_level:
    warning: 2
    error: 3

# Custom rules focused on design system enforcement
custom_rules:
  no_literal_rgb_colors:
    name: "No literal RGB/white Color initializer"
    regex: "\\bColor\\s*\\(\\s*(red|green|blue|white)\\s*:"
    message: "Use AppColors tokens (semantic colors) instead of literal RGB/white initializers."
    included:
      - I Do Blueprint/Views
      - I Do Blueprint/I Do Blueprint/Views
      - I Do Blueprint/App
      - I Do Blueprint/Services
    excluded:
      - I Do Blueprint/Design/ColorPalette.swift
      - I Do Blueprint/Domain
    severity: warning

  no_basic_foreground_colors:
    name: "No basic foregroundColor(.gray/.black/.white)"
    regex: "\\.foregroundColor\\s*\\(\\s*\\.(black|white|gray)\\s*\\)"
    message: "Use semantic colors from AppColors (e.g., textPrimary/textSecondary/primary)."
    included:
      - I Do Blueprint/Views
      - I Do Blueprint/I Do Blueprint/Views
      - I Do Blueprint/App
      - I Do Blueprint/Services
    severity: warning

  # no_numeric_padding:  # Disabled: sometimes numeric padding is appropriate
  #   name: "No numeric padding"
  #   regex: "\\.padding\\s*\\(\\s*(?:\\.[A-Za-z]+\\s*,\\s*)?\\d+(?:\\.\\d+)?\\s*\\)"
  #   message: "Use Spacing.* tokens instead of numeric literals in padding."
  #   included:
  #     - I Do Blueprint/Views
  #     - I Do Blueprint/I Do Blueprint/Views
  #     - I Do Blueprint/App
  #     - I Do Blueprint/Services
  #   severity: warning

  no_custom_font:
    name: "No .font(.custom)"
    regex: "\\.font\\s*\\(\\s*\\.custom\\s*\\("
    message: "Use Typography tokens instead of .font(.custom)."
    included:
      - I Do Blueprint/Views
      - I Do Blueprint/I Do Blueprint/Views
      - I Do Blueprint/App
      - I Do Blueprint/Services
    severity: warning
