//
//  FileImportService.swift
//  I Do Blueprint
//
//  Façade service for file import operations
//  Composes focused services for CSV/XLSX parsing, validation, mapping, and conversion
//

import Foundation
import AppKit
import CoreXLSX

// MARK: - Import Models

struct ImportPreview {
    let headers: [String]
    let rows: [[String]]
    let totalRows: Int
    let fileName: String
    let fileType: FileType

    enum FileType: String {
        case csv = "CSV"
        case xlsx = "XLSX"
    }
}

struct ImportValidationResult {
    let isValid: Bool
    let errors: [ImportError]
    let warnings: [ImportWarning]

    struct ImportError {
        let row: Int
        let column: String
        let message: String
    }

    struct ImportWarning {
        let row: Int
        let column: String
        let message: String
    }
}

struct ColumnMapping {
    let sourceColumn: String
    let targetField: String
    let isRequired: Bool
}

// MARK: - File Import Service (Façade)

/// Façade service that composes focused import services
/// Maintains backward compatibility while delegating to specialized services
@MainActor
final class FileImportService {
    
    // MARK: - Composed Services
    
    private let csvService: CSVImportService
    private let xlsxService: XLSXImportService
    private let validationService: ImportValidationService
    private let mappingService: ColumnMappingService
    private let guestConversionService: GuestConversionService
    private let vendorConversionService: VendorConversionService
    
    // MARK: - Initialization
    
    init(
        csvService: CSVImportService = CSVImportService(),
        xlsxService: XLSXImportService = XLSXImportService(),
        validationService: ImportValidationService = ImportValidationService(),
        mappingService: ColumnMappingService = ColumnMappingService(),
        guestConversionService: GuestConversionService = GuestConversionService(),
        vendorConversionService: VendorConversionService = VendorConversionService()
    ) {
        self.csvService = csvService
        self.xlsxService = xlsxService
        self.validationService = validationService
        self.mappingService = mappingService
        self.guestConversionService = guestConversionService
        self.vendorConversionService = vendorConversionService
    }
    
    // MARK: - Public Interface (Delegates to Services)
    
    /// Parse CSV file and return preview
    func parseCSV(from url: URL) async throws -> ImportPreview {
        return try await csvService.parseCSV(from: url)
    }
    
    /// Parse XLSX file and return preview
    func parseXLSX(from url: URL) async throws -> ImportPreview {
        return try await xlsxService.parseXLSX(from: url)
    }
    
    /// Validate import data against column mappings
    func validateImport(
        preview: ImportPreview,
        mappings: [ColumnMapping]
    ) -> ImportValidationResult {
        return validationService.validateImport(preview: preview, mappings: mappings)
    }
    
    /// Infer column mappings based on header names
    func inferMappings(headers: [String], targetFields: [String]) -> [ColumnMapping] {
        return mappingService.inferMappings(headers: headers, targetFields: targetFields)
    }
    
    /// Convert CSV rows to Guest objects using column mappings
    func convertToGuests(
        preview: ImportPreview,
        mappings: [ColumnMapping],
        coupleId: UUID
    ) -> [Guest] {
        return guestConversionService.convertToGuests(
            preview: preview,
            mappings: mappings,
            coupleId: coupleId
        )
    }
    
    /// Convert CSV rows to Vendor objects using column mappings
    func convertToVendors(
        preview: ImportPreview,
        mappings: [ColumnMapping],
        coupleId: UUID
    ) -> [VendorImportData] {
        return vendorConversionService.convertToVendors(
            preview: preview,
            mappings: mappings,
            coupleId: coupleId
        )
    }
}

// MARK: - Vendor Import Data

/// Temporary struct for vendor import data (before database insertion)
/// Vendor uses Int64 ID which is auto-generated by database
struct VendorImportData: Codable {
    let vendorName: String
    let vendorType: String?
    let vendorCategoryId: String?
    let contactName: String?
    let phoneNumber: String?
    let email: String?
    let website: String?
    let notes: String?
    let quotedAmount: Double?
    let imageUrl: String?
    let isBooked: Bool?
    let dateBooked: Date?
    let budgetCategoryId: UUID?
    let coupleId: UUID
    let isArchived: Bool
    let includeInExport: Bool
    let streetAddress: String?
    let streetAddress2: String?
    let city: String?
    let state: String?
    let postalCode: String?
    let country: String?
    let latitude: Double?
    let longitude: Double?
}


// MARK: - File Import Errors

enum FileImportError: Error, LocalizedError {
    case emptyFile
    case parsingFailed(underlying: Error)
    case xlsxNotSupported
    case invalidFileType
    case fileAccessDenied

    var errorDescription: String? {
        switch self {
        case .emptyFile:
            return "The file is empty or contains no data"
        case .parsingFailed(let error):
            return "Failed to parse file: \(error.localizedDescription)"
        case .xlsxNotSupported:
            return "XLSX import is not yet supported. Please use CSV format."
        case .invalidFileType:
            return "Invalid file type. Please select a CSV or XLSX file."
        case .fileAccessDenied:
            return "Unable to access the file. Please check permissions."
        }
    }
}
