//
//  VendorConversionService.swift
//  I Do Blueprint
//
//  Service for converting import data to Vendor objects
//

import Foundation

/// Protocol for vendor conversion operations
protocol VendorConversionProtocol {
    func convertToVendors(preview: ImportPreview, mappings: [ColumnMapping], coupleId: UUID) -> [VendorImportData]
}

/// Service responsible for converting CSV/XLSX rows to Vendor objects
final class VendorConversionService: VendorConversionProtocol {
    private let logger = AppLogger.general
    
    // MARK: - Public Interface
    
    /// Convert CSV rows to Vendor objects using column mappings
    /// Note: Vendor ID is Int64 and auto-generated by database, so we don't set it here
    func convertToVendors(
        preview: ImportPreview,
        mappings: [ColumnMapping],
        coupleId: UUID
    ) -> [VendorImportData] {
        var vendors: [VendorImportData] = []
        let now = Date()
        
        logger.info("Converting vendors: \(preview.rows.count) rows, \(mappings.count) mappings")
        
        for row in preview.rows {
            // Skip rows with wrong column count
            guard row.count == preview.headers.count else { continue }
            
            // Extract values using mappings
            let values = extractValues(from: row, headers: preview.headers, mappings: mappings)
            
            // Required field
            guard let vendorName = values["vendorName"]?.trimmingCharacters(in: .whitespaces),
                  !vendorName.isEmpty else {
                continue
            }
            
            // Create vendor import data object
            let vendorData = VendorImportData(
                vendorName: vendorName,
                vendorType: values["vendorType"]?.trimmingCharacters(in: .whitespaces).nilIfEmpty,
                vendorCategoryId: values["vendorCategoryId"]?.trimmingCharacters(in: .whitespaces).nilIfEmpty,
                contactName: values["contactName"]?.trimmingCharacters(in: .whitespaces).nilIfEmpty,
                phoneNumber: values["phoneNumber"]?.trimmingCharacters(in: .whitespaces).nilIfEmpty,
                email: values["email"]?.trimmingCharacters(in: .whitespaces).nilIfEmpty,
                website: values["website"]?.trimmingCharacters(in: .whitespaces).nilIfEmpty,
                notes: values["notes"]?.trimmingCharacters(in: .whitespaces).nilIfEmpty,
                quotedAmount: values["quotedAmount"].flatMap { DateParsingHelpers.parseNumeric($0) },
                imageUrl: values["imageUrl"]?.trimmingCharacters(in: .whitespaces).nilIfEmpty,
                isBooked: DateParsingHelpers.parseBoolean(values["isBooked"] ?? ""),
                dateBooked: values["dateBooked"].flatMap { DateParsingHelpers.parseDate($0) },
                budgetCategoryId: values["budgetCategoryId"].flatMap { UUID(uuidString: $0) },
                coupleId: coupleId,
                isArchived: false,
                includeInExport: DateParsingHelpers.parseBoolean(values["includeInExport"] ?? "") ?? false,
                streetAddress: values["streetAddress"]?.trimmingCharacters(in: .whitespaces).nilIfEmpty,
                streetAddress2: values["streetAddress2"]?.trimmingCharacters(in: .whitespaces).nilIfEmpty,
                city: values["city"]?.trimmingCharacters(in: .whitespaces).nilIfEmpty,
                state: values["state"]?.trimmingCharacters(in: .whitespaces).nilIfEmpty,
                postalCode: values["postalCode"]?.trimmingCharacters(in: .whitespaces).nilIfEmpty,
                country: values["country"]?.trimmingCharacters(in: .whitespaces).nilIfEmpty ?? "US",
                latitude: values["latitude"].flatMap { DateParsingHelpers.parseNumeric($0) },
                longitude: values["longitude"].flatMap { DateParsingHelpers.parseNumeric($0) }
            )
            
            vendors.append(vendorData)
        }
        
        logger.info("Converted \(vendors.count) vendors from import")
        return vendors
    }
    
    // MARK: - Private Helpers
    
    /// Extract values from row using mappings
    private func extractValues(from row: [String], headers: [String], mappings: [ColumnMapping]) -> [String: String] {
        var values: [String: String] = [:]
        for mapping in mappings {
            if let columnIndex = headers.firstIndex(of: mapping.sourceColumn) {
                values[mapping.targetField] = row[columnIndex]
            }
        }
        return values
    }
}

// MARK: - String Extension

private extension String {
    var nilIfEmpty: String? {
        let trimmed = self.trimmingCharacters(in: .whitespaces)
        return trimmed.isEmpty ? nil : trimmed
    }
}
